spring:
  # redis配置
  redis:
    host: 192.168.158.164
    port: 6379
    password: yueliminvc@outlook.com
    timeout: 10000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 10000
      shutdown-timeout: 100
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.158.164:3306/minio?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: yueliminvc@outlook.com
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          slow-sql-millis: 1
          log-slow-sql: true
      filters: config,stat,wall,log4j2
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.css,*.ioc,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 白名单
        allow: 127.0.0.1
        # 黑名单
        deny: 192.168.158.1
        reset-enable: false
        login-password: yueliminvc@outlook.com
        login-username: yueliminvc@outlook.com
      aop-patterns: com.minio.service.*

# MybatisPlus
mybatis-plus:
  configuration:
    cache-enabled: false
    # 驼峰转换
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: auto
  # 扫描实体类
  type-aliases-package: com.minio.entity
  # 扫描自定义SQL
  mapper-locations: classpath:com/minio/mapper/*.xml

# minio配置
minio:
  endpoint: http://192.168.158.164:9000
  accessKey: yueliminvc@outlook.com
  secretKey: yueliminvc@outlook.com
  bucketImageName: min-io
  serviceName: p2p

# 开启Swagger注解
swagger:
  enable: true
